//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryTradeMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart_order_detail
    {
        public int id { get; set; }
        public string order_id { get; set; }
        public int state { get; set; }
        public string product_customize_id { get; set; }
        public string product_name { get; set; }
        public decimal quantity { get; set; }
        public decimal price { get; set; }
        public string unit_name { get; set; }
        public decimal total { get; set; }
        public decimal tax_rate { get; set; }
        public int tax_add { get; set; }
        public decimal tax_total { get; set; }
        public string memo { get; set; }
        public System.DateTime update_date { get; set; }
    }
}
