//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryTradeMarket
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TradeMarketEntities : DbContext
    {
        public TradeMarketEntities()
            : base("name=TradeMarketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cart_order> cart_order { get; set; }
        public virtual DbSet<cart_order_detail> cart_order_detail { get; set; }
        public virtual DbSet<department> department { get; set; }
        public virtual DbSet<member> member { get; set; }
        public virtual DbSet<member_type> member_type { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<product_on_sales> product_on_sales { get; set; }
        public virtual DbSet<product_type> product_type { get; set; }
        public virtual DbSet<supply> supply { get; set; }
        public virtual DbSet<error_log> error_log { get; set; }
        public virtual DbSet<product_unit> product_unit { get; set; }
        public virtual DbSet<temp_cart> temp_cart { get; set; }
    }
}
