//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryTradeMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class member
    {
        public int id { get; set; }
        public int role { get; set; }
        public int type_id { get; set; }
        public string member_name { get; set; }
        public string account { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string mobile { get; set; }
        public string tel { get; set; }
        public string fax { get; set; }
        public int state { get; set; }
        public string contact_address_city_o { get; set; }
        public string contact_address_area_o { get; set; }
        public string contact_address_street_o { get; set; }
        public string contact_address_o { get; set; }
        public string contact_address_zipno_o { get; set; }
        public System.DateTime update_date { get; set; }
        public string update_user_name { get; set; }
    }
}
